name: justdropd

services:
  - name: backend
    github:
      repo: shopia-hacks/Just-Dropd
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: node-js
    build_command: npm install
    run_command: npm start
    http_port: 8080
    envs:
      - key: NODE_ENV
        value: production

static_sites:
  - name: frontend
    github:
      repo: shopia-hacks/Just-Dropd
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: flutter build web --release
    output_dir: build/web